name: Linter
on: [push]
jobs:
  runs-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop
